name: music_up
description: A music management tool for Linux, written in Flutter.

# Maintainer Information
maintainer: Michael Milke (Nobo)
maintainer_email: nobo_code@posteo.de
repository: https://github.com/hiphopconnect/musicup/
version: 2.2.0+10

publish_to: 'none' # Do not publish this package.

environment:
  sdk: ">=3.0.0 <4.0.0"      # ZURÜCK auf kompatible Version
  flutter: ">=3.10.0"        # ZURÜCK auf kompatible Version

dependencies:
  flutter:
    sdk: flutter
  # STABILE Dependencies die funktionieren:
  # Core Dependencies (stable versions)
  path_provider: ^2.1.1
  file_picker: ^8.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.2
  uuid: ^4.5.0
  share_plus: ^10.0.2
  cross_file: ^0.3.4+2
  csv: ^6.0.0
  xml: ^6.1.0
  logger: ^1.4.0              # Stable version
  package_info_plus: ^8.1.1
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.13
  path_provider_platform_interface: ^2.1.2
  test: ^1.24.9
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#2E4F2E" # Dunkelgrün wie das Logo
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/music_up_icon.png
    - assets/icons/app_icon.png