name: music_up
description: A new Flutter project.

publish_to: 'none' # Do not publish this package.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  file_picker: ^8.1.2
  shared_preferences: ^2.1.0
  uuid: ^4.5.0
  share_plus: ^10.0.2
  cross_file: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/music_up_icon.png
