name: music_up
description: A music management tool for Linux, written in Flutter.

# Maintainer Information
maintainer: Michael Milke (Nobo)
maintainer_email: nobo_code@posteo.de
repository: https://github.com/hiphopconnect/musicup/
version: 1.3.1+5

publish_to: 'none' # Do not publish this package.

environment:
  sdk: ">=3.0.0 <4.0.0"      # ZURÜCK auf kompatible Version
  flutter: ">=3.10.0"        # ZURÜCK auf kompatible Version

dependencies:
  flutter:
    sdk: flutter
  # STABILE Dependencies die funktionieren:
  path_provider: ^2.1.1       # Stabil
  file_picker: ^8.1.2         # Deine ursprüngliche Version war OK
  path: ^1.8.3                # Stabil
  shared_preferences: ^2.2.2  # Stabil
  uuid: ^4.5.0                # Stabil
  share_plus: ^10.0.2         # Deine ursprüngliche Version war OK
  cross_file: ^0.3.4+2        # OK
  csv: ^6.0.0                 # OK
  xml: ^6.1.0                 # Stabil
  logger: ^1.4.0              # Stabil (nicht 2.x!)
  package_info_plus: ^8.1.1   # OK
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4             # Kompatible Version
  build_runner: ^2.4.13       # Kompatible Version
  path_provider_platform_interface: ^2.1.2
  test: ^1.24.9               # DOWNGRADE: Kompatible Version! 🎯
  flutter_lints: ^5.0.0       # Stabil
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#2E4F2E" # Dunkelgrün wie das Logo
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/music_up_icon.png
    - assets/icons/app_icon.png