name: music_up
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  file_picker: ^5.2.1
  shared_preferences: ^2.0.6
  uuid: ^3.0.4


  # Weitere Abhängigkeiten können hier hinzugefügt werden

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/music_up_icon.png
