name: music_up
description: A music management tool for Linux, written in Flutter.

# Maintainer Information
maintainer: Michael Milke (Nobo)
maintainer_email: nobo_code@posteo.de
repository: https://github.com/hiphopconnect/musicup/
version: 1.2.0+1

publish_to: 'none' # Do not publish this package.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  file_picker: ^8.1.2
  shared_preferences: ^2.1.0
  uuid: ^4.5.0
  share_plus: ^10.0.2
  cross_file: ^0.3.2
  csv: ^6.0.0
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.3.3
  path_provider_platform_interface: ^2.0.4
  test: ^1.16.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/music_up_icon.png
