name: musicup
version: '2.1.2'
summary: Music collection manager with Discogs integration
description: |
  MusicUp is a cross-platform music collection management application that helps you 
  organize your vinyl records, CDs, and digital albums. With integrated Discogs search, 
  you can easily add detailed album information to your collection.
  
  Features:
  - Complete collection management
  - Discogs integration for album data
  - Import/Export in multiple formats (JSON, CSV, XML)
  - Advanced filtering and search
  - Wantlist management
  - Privacy-first: all data stored locally
  - Cross-platform compatibility

grade: stable
confinement: strict
base: core22
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  musicup:
    command: music_up
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - wayland

parts:
  musicup:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
    stage-packages:
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libcairo2
      - libpango-1.0-0
      - libharfbuzz0b
      - libatk1.0-0